apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      service: postgres
    name: postgres
  spec:
    replicas: 1
    selector: 
      matchLabels:
        service: postgres
    template:
      metadata:
        labels:
          service: postgres
      spec:
        containers:
          image: postgres
          name: postgres
          env:
          - name: POSTGRES_DB
            value: "tukano"
          - name: POSTGRES_USER
            value: "tukano"
          - name: POSTGRES_PASSWORD
            value: "tukano"
    
      restartPolicy: Always