apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      service: postgres
    name: postgres
  spec:
    replicas: 1
    selector: 
      matchLabels:
        service: postgres
    template:
      metadata:
        labels:
          service: postgres
      spec:
        containers:
          env:
            - name: REDIS_KEY
              valueFrom:
                secretKeyRef:
                  name: tukano-secrets
                  key: REDIS_KEY

          image: postgres
          name: postgres
      
      restartPolicy: Always