apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
        - image: redis
          name: redis
          args:
            - redis-server
            - --requirepass
            - "sportingale"

      restartPolicy: Always
