apiVersion: v1
kind: Service
metadata:
  name: storage
  labels:
    app: storage
spec:
  selector:
    app: storage
  ports:
    - name: storage
      port: 6789
      targetPort: 6789
  type: LoadBalancer
