apiVersion: apps/v1
kind: Deployment
metadata:
  name: tukano
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tukano
  template:
    metadata:
      labels:
        app: tukano
    spec:
      containers:
        - image: mlatas29/tukano
          name: tukano
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: STORAGE
              value: "http://48.209.144.67:8080/blobs-1/rest"
      restartPolicy: Always
