apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: tukano
  name: tukano
spec:
  replicas: 1
  selector:
    matchLabels:
      service: tukano
  template:
    metadata:
      labels:
        service: tukano
    spec:
      containers:
        - image: /tukano
          name: tukano
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: STORAGE
              value: "http://172.205.12.90:8080/blobs-1/rest"
      restartPolicy: Always
